theme = "catppuccin_mocha"

[editor]
auto-format = true
color-modes = true
completion-replace = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = true
rulers = [ 80, 100 ]
scrolloff = 8
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.statusline]
left = [ "mode", "file-name", "read-only-indicator", "file-modification-indicator", "version-control" ]
center = [ "workspace-diagnostics" ]

[editor.whitespace]
tab = "→"
tabpad = "·"

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"

A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

"$" = ["select_mode", "goto_line_end", "normal_mode"]
"^" = ["select_mode", "goto_line_start", "normal_mode"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

"$" = "goto_line_end"
"^" = "goto_line_start"
