[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.neocmakelsp]
command = "neocmakelsp"
args = ["--stdio"]

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]
config.reportMissingtypeStubs = false

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.rust-analyzer.config]
cargo.allFeatures = true
cargo.buildScripts = true
cargo.extraArgs = [ "--profile", "rust-analyzer" ]
cargo.extraEnv = { CARGO_PROFILE_RUST_ANALYZER_INHERITS = "dev" }
check.command = "clippy"
checkOnSave = true
procMacro.enable = true
timeout = 30

[language-server.ruff-lsp.config]
documentFormatting = true 
settings.run = "onSave"

[[language]]
name = "cmake"
auto-format = true
language-servers = [{ name = "neocmakelsp" }]

[[language]]
name = "gjs"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "gts"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "javascript"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "ruff-lsp", only-features = [ "format", "diagnostics" ] },
  { name = "pyright", except-features = [ "format", "diagnostics" ] },
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "typescript"
language-servers = [ { name = "vtsls", except-features = [ "format" ] }, "biome" ]
auto-format = true


