[[language]]
name = "html"
file-types = ["html", "mjml"]
# formatter = { command = 'prettier', args = ["--parser", "hubl", "--plugin-search-dir", "/home/leonie/.local/share/pnpm/global/5/"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
# auto-format = true

[[language]]
name = "php"
roots = ["composer.lock"]
auto-format = true

[[language]]
name = "rust"

[language-server.rust-analyzer.config]
checkOnSave = true
check.command = "clippy"
cargo.allFeatures = true
cargo.buildScripts = true
cargo.extraEnv = { CARGO_PROFILE_RUST_ANALYZER_INHERITS = "dev" }
cargo.extraArgs = [ "--profile", "rust-analyzer" ]
procMacro.enable = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "vue"
formatter = { command = 'prettier', args = ["--parser", "vue"] }
auto-format = true

[[language]]
name = "xml"
file-types = ["xml", "xlf"]

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true

[language-server.yaml-language-server.config]
# https://github.com/redhat-developer/yaml-language-server#language-server-settings
yaml = { keyOrdering = false }

[[language]]
name = "env"
file-types = [".env", ".env.local", ".env.development", ".env.production", ".env.dist", ".envrc"]
