[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"
feature_paths = true          # enable path completion

# write logs to /tmp/completion.log
# [language-server.scls.environment]
# RUST_LOG = "info,simple-completion-langauge-server=info"
# LOG_FILE = "/tmp/completion.log"
# write logs to /tmp/completion.log

[language-server.rust-analyzer.config]
cargo.allFeatures = true
cargo.buildScripts = true
cargo.extraArgs = [ "--profile", "rust-analyzer" ]
cargo.extraEnv = { CARGO_PROFILE_RUST_ANALYZER_INHERITS = "dev" }
check.command = "clippy"
checkOnSave = true
procMacro.enable = true
timeout = 30

# append langage server to existed languages
# [[language]]
# name = "rust"
# language-servers = [ "scls", "rust-analyzer", "slint-lsp" ]
[[language]]
name = "rust"
language-servers = [ "scls", "rust-analyzer" ]

[[language]]
name = "slint"
language-servers = [ "scls", "slint-lsp" ]

[[language]]
name = "git-commit"
language-servers = [ "scls" ]

# introduce a new language to enable completion on any doc by forcing set language with :set-language stub
[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]

